### ISSUE TITLE
Should "x-max-v" header in Get Discovery Document endpoint be a simple integer string?

### ISSUE THREAD

**Issue by wcai-biza** [datarightplus/datarightplus-redocly#8]
Currently, "x-max-v" header in Get Discovery Document endpoint is defined as an enum with only one value "V1".

The concern is that when "V2" is introduced, and if client side picks it up before it is implemented on server side, and if server side is implemented in a strongly typed language, e.g. Java, then an unknown "V2" value can be rejected by server.

Also, "x-max-v" header is now optional. Should it be required?

**Comment by perlboy** [comment]
This is an interesting one. There's two options:
1. Change it to a pure string and imply an incrementing version number
2. Change it to an integer and set the version for this payload to be an integer as well.

(1) is the simplest and is what I've now merged in along with setting the header to mandatory. (2) though seems like it is probably the nicest for the endpoint but makes it inconsistent with all other endpoints. For now I've stuck with (1) and merged this https://github.com/datarightplus/datarightplus-redocly/pull/12
