### ISSUE TITLE
Discovery Document requestVersions/responseVersions V.S. CDS spec endpoint versions

### ISSUE THREAD

**Issue by wcai-biza** [datarightplus/datarightplus-redocly#9]
Are `requestVersions` and `responseVersions` supposed to reflect the endpoint versions? Or the request / response model versions? Because endpoint versions and request / response model versions are not always aligned, i.e. endpoint version may be bumped up without bumping up request / response model version.

For example, "Get Products" endpoint (`GET /banking/products`) have 3 endpoint versions, and the latest version is `3`. But the newest response model is `ResponseBankingProductListV2`. If a data holder only supports "Get Products" endpoint version 3, should `cds.endpoint.listBankingProducts.responseVersions` be `["V3"]` or `["V2"]`? Similarly, "Get Scheduled Payments For Specific Accounts" newest version is version `2`, but the request model is same as  version `1` (`RequestAccountIds`), should `cds.endpoint.listScheduledPaymentsSpecificAccounts.requestVersions` be `["V2"]` or `["V1"]`?

**Comment by perlboy** [comment]
The intent is that `responseVersions` be used for `x-v` with a prefix of `V` to maintain consistency. I've updated the draft through https://github.com/datarightplus/datarightplus-discovery/pull/1 to specifically spell that out in spec. Might be worth revisiting it again if it's still disliked but closing this for now.
